services:
  - type: web
    name: greenbite-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: uvicorn ml_api.ml_api_fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 